function [structArray, tab] = readOFData(filename)
% helper function to read OpenFace produced datafile
% https://github.com/TadasBaltrusaitis/OpenFace/wiki/Output-Format#featureextraction
    tab = readtable(filename);
    column_names = tab.Properties.VariableNames;

    all_params  = dlmread(filename, ',', 1, 0);
    valid_frames = logical(all_params(:,4));

    % read in pixel coords
    landmark_inds_x = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'x_'));
    landmark_inds_y = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'y_'));
    x_img = all_params(valid_frames, landmark_inds_x);
    y_img = all_params(valid_frames, landmark_inds_y);

    % 3d coords
    landmark_inds_X = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'X_'));
    landmark_inds_Y = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'Y_'));
    landmark_inds_Z = cellfun(@(x) ~isempty(x) && x==1, strfind(column_names, 'Z_'));
    x_3d = all_params(valid_frames, landmark_inds_X);
    y_3d = all_params(valid_frames, landmark_inds_Y);
    z_3d = all_params(valid_frames, landmark_inds_Z);
        
    tab = tab(valid_frames, :);  % remove bad frames from tab also
    
    for i = 1:sum(valid_frames)
        structArray(i) = struct( ...
                'frame',    tab.frame(i)    ...
            ,   'x_img',    x_img(i, :)     ...
            ,   'y_img',    y_img(i, :)     ...
            ,   'x_3d',     x_3d(i, :)      ...
            ,   'y_3d',     y_3d(i, :)      ...
            ,   'z_3d',     z_3d(i, :)      ...
            ,   'p_scale',  tab.p_scale(i)  ...
            ,   'p_tx',     tab.p_tx(i)     ...
            ,   'p_ty',     tab.p_ty(i)     ...
            ,   'p_rx',     tab.p_rx(i)     ...
            ,   'p_ry',     tab.p_ry(i)     ...
            ,   'p_rz',     tab.p_rz(i)     ...
            ,   'Tx',       tab.pose_Tx(i)  ...
            ,   'Ty',       tab.pose_Ty(i)  ...
            ,   'Tz',       tab.pose_Tz(i)  ...
            ,   'Rx',       tab.pose_Rx(i)  ...
            ,   'Ry',       tab.pose_Ry(i)  ...
            ,   'Rz',       tab.pose_Rz(i)  ...
        );
    end
    
end